#!/usr/bin/env python3
'''
def max(*args):
	args=sorted(args)
	a=args[-1]
	for n in args[:-1]:
		if n > a:
		   return n 
		else:
		    return a


print(max(1,6,2,34,5))


res=[]

def rec(a):
     for v in a:
         print(v)
         if  not isinstance(v,list):
                res.append(v)
         else:
                rec(v)
     return res


print(rec([1,2,3,[4,5],6,[7,[2,[1]],3]]))



def bcd(a,b):
	while a!=0 and b!=0:
		if a > b :
		 a=a%b
		else:
		 b=b%a
	return a+b

print(bcd(10,3)) 
'''
